name = "emergent-app"
main = "src/worker.js"
compatibility_date = "2025-01-01"
workers_dev = true

[build]
# biar Cloudflare ngebuild frontend sebelum deploy
command = "cd frontend && yarn install --frozen-lockfile || npm ci && yarn build || npm run build"

[assets]
# PENTING: ini folder hasil build CRA
directory = "./frontend/build"

# (opsional) map ke domain
# [[routes]]
# pattern = "app.example.com/*"
# zone_name = "example.com"
